apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: "/etc/config"
      name: config-volume
  volumes:
  - name: config-volume
    configMap:
      name: app-config