apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
        tier: web
    spec:
      containers:
      - name: flask
        image: tiangolo/uwsgi-nginx-flask:python3.8
        env:
        - name: FLASK_ENV
          value: "development"
        ports:
        - containerPort: 80