apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo-pod
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: "/host-data"
      name: host-storage
  volumes:
  - name: host-storage
    hostPath:
      path: "/mnt/data"
      type: DirectoryOrCreate