apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo-pod
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: "/tmp/data"
      name: temp-storage
  volumes:
  - name: temp-storage
    emptyDir: {}