apiVersion: v1
kind: Pod
metadata:
  name: secure-app
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: config-volume
          mountPath: "/config"
        - name: secret-volume
          mountPath: "/secret"
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: app-config
    - name: secret-volume
      secret:
        secretName: app-secret
