apiVersion: v1
kind: Pod
metadata:
  name: low-priority
  namespace: eviction-lab
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 600"]
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"