apiVersion: v1
kind: Pod
metadata:
  name: memory-stress
  namespace: eviction-lab
spec:
  containers:
  - name: memory-stress
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "2", "--vm-bytes", "1G", "--timeout", "120s"]
    resources:
      requests:
        memory: "500Mi"
      limits:
        memory: "1Gi"