apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-curl-test
spec:
  podSelector:
    matchLabels:
      app: my-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              run: curl-test
      ports:
        - protocol: TCP
          port: 80