apiVersion: v1
kind: Pod
metadata:
  name: storage-stress
  namespace: eviction-lab
spec:
  containers:
  - name: storage-stress
    image: busybox
    command: ["sh", "-c", "dd if=/dev/zero of=/data/bigfile bs=1M count=2048; sleep 300"]
    volumeMounts:
    - name: ephemeral-storage
      mountPath: /data
    resources:
      requests:
        ephemeral-storage: "200Mi"
      limits:
        ephemeral-storage: "500Mi"
  volumes:
  - name: ephemeral-storage
    emptyDir: {}